spring.application.name=dc

# Conexão com o banco de dados Neon (PostgreSQL)
spring.datasource.url=jdbc:postgresql://ep-dry-brook-ae35vz4x-pooler.c-2.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_pcOFt2PXiVw5
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
